### ISSUE TITLE
Error with "Test API"

### ISSUE THREAD

**Issue by PascalsHere** [kylierst/MSO_E5_Dev_AutoRenew#12]
`Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 11
    ***
          ^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.`

**Comment by Harsh-2002** [comment]
fix issue with your Github Action Secrets

**Comment by PascalsHere** [comment]
> fix issue with your Github Action Secrets

I tried re-adding them, but it still dose not work.

**Comment by Harsh-2002** [comment]
share screenshot how you are adding...

**Comment by kylierst** [comment]
> fix issue with your Github Action Secrets

Yes, this is correct. I encountered this also and this occurred due to python unable to read "Curly quotes" when adding the secret variables in action secrets. Make sure that you use proper quotes "Straight quotes" otherwise there will be a syntax error like this. Also make sure that there are no extra spaces
